#!/usr/bin/env php
<?php

if (version_compare(PHP_VERSION, '5.4.0', '<')) {
    die("\033[0;31mThis PHP binary is not version 5.4 or greater.\033[0m\n");
}

$options = getopt("", array('host::', 'port::'));

$host = empty($options['host']) ? 'localhost' : $options['host'];

$port = empty($options['port']) ? 8000 : $options['port'];

$public = __DIR__ . '/public';
$server = __DIR__ . '/server.php';


echo "\033[0;32mWeb app development server started on http://{$host}:{$port}\033[0m\n";

passthru('"' . PHP_BINARY . '"' . " -S {$host}:{$port} -t \"{$public}\" \"{$server}\"", $return_var);